-- MySQL Script generated by MySQL Workbench
-- Mon Apr 16 16:42:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema munisanborja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema munisanborja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `munisanborja` DEFAULT CHARACTER SET utf8 ;
USE `munisanborja` ;

-- -----------------------------------------------------
-- Table `munisanborja`.`estadotramite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `munisanborja`.`estadotramite` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `munisanborja`.`estadoviabilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `munisanborja`.`estadoviabilidad` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `munisanborja`.`costobeneficio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `munisanborja`.`costobeneficio` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `valorActualNeto` DOUBLE NULL DEFAULT NULL,
  `tasaInternaRetorno` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `munisanborja`.`costoefectividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `munisanborja`.`costoefectividad` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `ratio` DOUBLE NULL DEFAULT NULL,
  `unidadMedida` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `munisanborja`.`montoinversiontotal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `munisanborja`.`montoinversiontotal` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `precioMercado` DOUBLE NULL DEFAULT NULL,
  `precioSocial` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `munisanborja`.`RequerimientoEvaluado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `munisanborja`.`RequerimientoEvaluado` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `impuestoRenta` DOUBLE NULL DEFAULT '0',
  `cManoObraCalificada` DOUBLE NULL DEFAULT '0',
  `cManoObraNoCalificada` DOUBLE NULL DEFAULT '0',
  `factorManoObraCalificada` DOUBLE NULL DEFAULT '0',
  `factorManoObraNoCalificada` DOUBLE NULL DEFAULT '0',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `munisanborja`.`ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `munisanborja`.`ubicacion` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(100) NOT NULL,
  `provincia` VARCHAR(100) NOT NULL,
  `localidad` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `munisanborja`.`unidadformuladora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `munisanborja`.`unidadformuladora` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `munisanborja`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `munisanborja`.`persona` (
  `idPersona` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(500) NOT NULL,
  `apellido` VARCHAR(500) NOT NULL,
  `numeroDocumento` VARCHAR(50) NOT NULL,
  `tipodocumento_idTipoDocumento` INT(11) NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `munisanborja`.`Requerimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `munisanborja`.`Requerimiento` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `identificador` VARCHAR(7) NULL DEFAULT NULL,
  `nombre` VARCHAR(500) NULL DEFAULT NULL,
  `objetivo` VARCHAR(500) NULL DEFAULT NULL,
  `problema` TEXT NULL DEFAULT NULL,
  `fuenteFinanciamiento` VARCHAR(500) NULL DEFAULT NULL,
  `programaInversion` TINYINT(4) NULL DEFAULT NULL,
  `analisisSostenibilidad` LONGTEXT NULL DEFAULT NULL,
  `unidadEjecutoraRecomendada` VARCHAR(500) NULL DEFAULT NULL,
  `costoOperacion` DOUBLE NULL DEFAULT NULL,
  `costoMantenimiento` DOUBLE NULL DEFAULT NULL,
  `fechaCreacion` DATE NULL DEFAULT NULL,
  `fechaActualizacion` DATE NULL DEFAULT NULL,
  `fechaAprobacion` DATE NULL DEFAULT NULL,
  `fechaRechazo` DATE NULL DEFAULT NULL,
  `elaboradoPor` VARCHAR(100) NULL DEFAULT NULL,
  `aprobadoPor` VARCHAR(100) NULL DEFAULT NULL,
  `revisadoPor` VARCHAR(100) NULL DEFAULT NULL,
  `EstadoTramite_codigo` INT(11) NOT NULL,
  `UnidadFormuladora_codigo` INT(11) NOT NULL,
  `MontoInversionTotal_codigo` INT(11) NOT NULL,
  `CostoBeneficio_codigo` INT(11) NOT NULL,
  `CostoEfectividad_codigo` INT(11) NOT NULL,
  `Ubicacion_codigo` INT(11) NOT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `RequerimientoEvaluado_codigo` INT(11) NULL DEFAULT NULL,
  `persona_idPersona` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_Requerimiento_EstadoTramite1_idx` (`EstadoTramite_codigo` ASC),
  INDEX `fk_Requerimiento_UnidadFormuladora1_idx` (`UnidadFormuladora_codigo` ASC),
  INDEX `fk_Requerimiento_MontoInversionTotal1_idx` (`MontoInversionTotal_codigo` ASC),
  INDEX `fk_Requerimiento_CostoBeneficio1_idx` (`CostoBeneficio_codigo` ASC),
  INDEX `fk_Requerimiento_CostoEfectividad1_idx` (`CostoEfectividad_codigo` ASC),
  INDEX `fk_Requerimiento_Ubicacion1_idx` (`Ubicacion_codigo` ASC),
  INDEX `fk_Requerimiento_RequerimientoEvaluado1_idx` (`RequerimientoEvaluado_codigo` ASC),
  INDEX `fk_Requerimiento_persona1_idx` (`persona_idPersona` ASC),
  CONSTRAINT `fk_Requerimiento_CostoBeneficio1`
    FOREIGN KEY (`CostoBeneficio_codigo`)
    REFERENCES `munisanborja`.`costobeneficio` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Requerimiento_CostoEfectividad1`
    FOREIGN KEY (`CostoEfectividad_codigo`)
    REFERENCES `munisanborja`.`costoefectividad` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Requerimiento_EstadoTramite1`
    FOREIGN KEY (`EstadoTramite_codigo`)
    REFERENCES `munisanborja`.`estadotramite` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Requerimiento_MontoInversionTotal1`
    FOREIGN KEY (`MontoInversionTotal_codigo`)
    REFERENCES `munisanborja`.`montoinversiontotal` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Requerimiento_RequerimientoEvaluado1`
    FOREIGN KEY (`RequerimientoEvaluado_codigo`)
    REFERENCES `munisanborja`.`RequerimientoEvaluado` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Requerimiento_Ubicacion1`
    FOREIGN KEY (`Ubicacion_codigo`)
    REFERENCES `munisanborja`.`ubicacion` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Requerimiento_UnidadFormuladora1`
    FOREIGN KEY (`UnidadFormuladora_codigo`)
    REFERENCES `munisanborja`.`unidadformuladora` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Requerimiento_persona1`
    FOREIGN KEY (`persona_idPersona`)
    REFERENCES `munisanborja`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `munisanborja`.`rubro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `munisanborja`.`rubro` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `presupuestoAsignado` DOUBLE NULL DEFAULT NULL,
  `totalComprometido` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `munisanborja`.`proyectopreinversion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `munisanborja`.`proyectopreinversion` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `identificador` VARCHAR(6) NOT NULL,
  `fechaInicio` DATE NULL DEFAULT NULL,
  `fechafin` DATE NULL DEFAULT NULL,
  `fechaDeclaracionViabilidad` DATE NULL DEFAULT NULL,
  `MontoComprometido` DOUBLE NULL DEFAULT '0',
  `MontoDevengado` DOUBLE NULL DEFAULT '0',
  `MontoEjecutado` DOUBLE NULL DEFAULT '0',
  `EstadoTramite_codigo` INT(11) NOT NULL,
  `Requerimiento_codigo` INT(11) NOT NULL,
  `EstadoViabilidad_codigo` INT(11) NOT NULL,
  `Rubro_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_ProyectoPreInversion_Requerimiento1_idx` (`Requerimiento_codigo` ASC),
  INDEX `fk_ProyectoPreInversion_EstadoTramite1_idx` (`EstadoTramite_codigo` ASC),
  INDEX `fk_ProyectoPreInversion_EstadoViabilidad1_idx` (`EstadoViabilidad_codigo` ASC),
  INDEX `fk_ProyectoPreInversion_Rubro1_idx` (`Rubro_codigo` ASC),
  CONSTRAINT `fk_ProyectoPreInversion_EstadoTramite1`
    FOREIGN KEY (`EstadoTramite_codigo`)
    REFERENCES `munisanborja`.`estadotramite` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProyectoPreInversion_EstadoViabilidad1`
    FOREIGN KEY (`EstadoViabilidad_codigo`)
    REFERENCES `munisanborja`.`estadoviabilidad` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProyectoPreInversion_Requerimiento1`
    FOREIGN KEY (`Requerimiento_codigo`)
    REFERENCES `munisanborja`.`Requerimiento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProyectoPreInversion_Rubro1`
    FOREIGN KEY (`Rubro_codigo`)
    REFERENCES `munisanborja`.`rubro` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `munisanborja`.`informetecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `munisanborja`.`informetecnico` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `fechaCreacion` DATE NULL DEFAULT NULL,
  `fechaAprobacion` DATE NULL DEFAULT NULL,
  `fechaActualizacion` DATE NULL DEFAULT NULL,
  `elaboradoPor` VARCHAR(45) NULL DEFAULT NULL,
  `revisadoPor` VARCHAR(45) NULL DEFAULT NULL,
  `aprobadoPor` VARCHAR(45) NULL DEFAULT NULL,
  `ProyectoPreInversion_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_informetecnico_proyectopreinversion1_idx` (`ProyectoPreInversion_codigo` ASC),
  CONSTRAINT `fk_informetecnico_proyectopreinversion1`
    FOREIGN KEY (`ProyectoPreInversion_codigo`)
    REFERENCES `munisanborja`.`proyectopreinversion` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `munisanborja`.`DetalleInformeTecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `munisanborja`.`DetalleInformeTecnico` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `concepto` VARCHAR(300) NULL DEFAULT NULL,
  `valor` DOUBLE NULL DEFAULT '0',
  `conclusion` VARCHAR(45) NULL DEFAULT NULL,
  `InformeTecnico_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_DetalleInformeTecnico_informetecnico1_idx` (`InformeTecnico_codigo` ASC),
  CONSTRAINT `fk_DetalleInformeTecnico_informetecnico1`
    FOREIGN KEY (`InformeTecnico_codigo`)
    REFERENCES `munisanborja`.`informetecnico` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `munisanborja`.`fuentefinanciamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `munisanborja`.`fuentefinanciamiento` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(300) NULL DEFAULT NULL,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `munisanborja`.`ubicacionvalida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `munisanborja`.`ubicacionvalida` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `munisanborja`.`unidadejecutoravalida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `munisanborja`.`unidadejecutoravalida` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
